# Promise

## es6 的Promise

Promise是一个构造函数。在函数内有all,race,reject,resolve

    var n = 1;
    var p = new Promise(function(resolve, reject){
        //做一些异步操作
        setTimeout(function(){
            n = n + 1;
            console.log(n);
            resolve(n);
        }, 2000);
    });

运行结果：

>2

其中resolve将Promise状态从Pending变为fullfiled(实现)，reject将Promise状态变成rejected(失败)

### resolve

这个对象在创建的阶段就立刻执行了方法，因此需要在外层包裹一个函数使用。

    var n = 1;
    var aysnc = ()=>{
        var p = new Promise(function(resolve, reject){
            //做一些异步操作
            setTimeout(function(){
                n = n+1;
                console.log(n);
                resolve(n);
            }, 2000);
        });
        return p;
    }
    aysnc();
   
将p返回出来，则可以调用.then(callb())方法，callb()将会获得resolve里的参数，

    aysnc().then(function(e){
        e = e+1;
        console.log(e); //3
    });

这其实就是回调函数的一个实现，类似的，我们也可以写出：

    var n = 1;
    var protest = (callback) =>{
        n = n+1;
        callback(n);
    }
    function add(){
        e = e+1;
        console.log(e);//3
    }
    protest(add);

但一旦出现多层回调，就会使得代码复杂度变大，阅读性变差，Promise可以继续用then方法对上次返回Promise对象继续执行操作（类似链式操作）。

    var n = 1;
    var aysnc1 = ()=>{
        var p = new Promise(function(resolve, reject){
            //做一些异步操作
            setTimeout(function(){
                n = n+1;
                console.log(n);
                resolve(n);
            }, 2000);
        });
        return p;
    }
    aysnc1().then((e)=>{
        console.log(e);
        return aysnc2();
        //这个函数与aysnc1是类似的，返回一个新定义的Promise对象
    }).then((e)=>{
        console.log(e);
    })


### reject

    var aysnc1 = ()=>{
        var p = new Promise(function(resolve, reject){
            //做一些异步操作
            Math.random()-0.5>0?resolve(1):reject(2)
        });
        return p;
    }
    aysnc1().then(
        (e)=>{console.log(e);},
        //1
        (e)=>{console.log(e);}
        //2，随机输出1或者2
    )


> reject和resolve不会中断函数的运行，可以使用return resolove()来中断函数。

### then

    是resolve的处理函数，then的参数是一个函数，该函数的参数就是之前的resolve传递的参数。

### catch

catch与trycatch类似可以用来将代码中的错误抛出，而不阻塞代码，同时也可以作为reject的回调

    aysn1().then(
        (e)=>{console.log(e);}
    )
    .catch(
        (e)=>{console.log(e);}
    )

### 回调

    const are = (resolve, reject) =>{
        return new Promise((resolve, reject) => {
            setTimeout(()=>{
                if(1){
                    resolve(1)
                } else {
                    reject(2)
                }
            },100);
        })
    }

    const bre = (resolve, reject) => {
        return new Promise((resolve, reject)=>{
            setTimeout(()=>{
                if(0){
                    console.log(3)
                } else {
                    console.log(4)
                }
            })
        })
    }
    are().then(a =>{
        console.log(a)
        return bre()
    })
    // .then(b =>{
    //     console.log(b)
    //     return bre()
    // })
    .then(b=>{
        console.log(b)
    })
    .catch(b=>{
        console.log(b)
    })

    // 回调中







